use_frameworks!
platform :ios, '10.0'

target 'CollapsedTableView_Example' do
  pod 'CollapsedTableView', :path => '../'

  target 'CollapsedTableView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
